server {
    listen 80;
    server_name n8n.joanmata.com;

    access_log /var/log/nginx/n8n_access.log;
    error_log  /var/log/nginx/n8n_error.log;

    location / {
        include conf.d/snippets/_authelia.conf;

        set $upstream_n8n n8n;
        proxy_pass         http://$upstream_n8n:5678;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        # Required for n8n websockets
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
    }
}
